---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cuberite
spec:
  selector:              
    matchLabels:                       
      app: cuberite
  replicas: 1
  template:
    metadata:
      labels:
        app: cuberite
    spec:
      containers:
      - image: rhysemmas/cuberite:armv7-3
        imagePullPolicy: Always
        name: server
        resources:
          requests:
            memory: 1Gi
            cpu: 2
        stdin: true
        tty: true
        ports:
        - name: minecraft
          containerPort: 25565
          protocol: TCP
        - name: web-admin
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /app/players
          name: players-pd
        - mountPath: /app/whitelist.sqlite
          name: allowlist-pd
        - mountPath: /app/world
          name: world-pd
        - mountPath: /app/world_nether
          name: world-nether-pd
        - mountPath: /app/world_the_end
          name: world-the-end-pd
      volumes:
      - name: players-pd
        hostPath:
          path: /mnt/players
          type: DirectoryOrCreate
      - name: allowlist-pd
        hostPath:
          path: /mnt/whitelist.sqlite
          type: FileOrCreate
      - name: world-pd
        hostPath:
          path: /mnt/world
          type: DirectoryOrCreate
      - name: world-nether-pd
        hostPath:
          path: /mnt/world_nether
          type: DirectoryOrCreate
      - name: world-the-end-pd
        hostPath:
          path: /mnt/world_the_end
          type: DirectoryOrCreate
      nodeSelector:
        minecraft: "true"
      tolerations:
      - key: minecraft
        operator: Exists
        effect: NoSchedule
