---
apiVersion: v1
kind: Service
metadata:
  name: cuberite
spec:
  ports:
    - name: server
      port: 25565
      targetPort: minecraft
      protocol: TCP
    - name: admin
      port: 25566
      targetPort: web-admin
  type: LoadBalancer
  selector:
    app: cuberite
